// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wtsghljhxtnvgderntdh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind0c2dobGpoeHRudmdkZXJudGRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNTg4ODMsImV4cCI6MjA1ODgzNDg4M30.gJfy0tZ8EvRz00djTAt2xx_BShu5NZ1uvPIWhiwLuDI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);